[package]
name = "fe310-monotonic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
e310x-hal = { version = "*" }
fugit = { version = "*" }
rtic-monotonic = { version = "*" }